# Copyright 2025 Xu Yan (EulbThgink), https://github.com/EulbThgink/Icenberg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# empty code ===========================================================================================================
EMPTY_CODE = 0x00

# view 2 model =========================================================================================================
VIEW_2_MODEL_BEGIN_CODE = 0x01

LOGIN_CODE = VIEW_2_MODEL_BEGIN_CODE + 0
USER_COMMAND_CODE = VIEW_2_MODEL_BEGIN_CODE + 1
LOGOUT_CODE = VIEW_2_MODEL_BEGIN_CODE + 2
REMOVE_AGENT_CODE = VIEW_2_MODEL_BEGIN_CODE + 3
REMOVE_SESSION_CODE = VIEW_2_MODEL_BEGIN_CODE + 4
LLM_ASK_CODE = VIEW_2_MODEL_BEGIN_CODE + 5
LLM_MODEL_CHECK = VIEW_2_MODEL_BEGIN_CODE + 6
SCROLL_WINDOW_CODE = VIEW_2_MODEL_BEGIN_CODE + 7
LLM_CHAT_HISTORY_REQ_CODE = VIEW_2_MODEL_BEGIN_CODE + 8
LLM_THREAD_STOP = VIEW_2_MODEL_BEGIN_CODE + 9
LLM_INLINE_MODEL_CHECK = VIEW_2_MODEL_BEGIN_CODE + 10
LLM_INLINE_ASK_CODE = VIEW_2_MODEL_BEGIN_CODE + 11
LLM_LOAD_CHAT_BY_HISTORY_IDX = VIEW_2_MODEL_BEGIN_CODE + 12
LLM_SERVER_URL_UPDATE_CODE = VIEW_2_MODEL_BEGIN_CODE + 13
RECONNECT_SHELL_CODE = VIEW_2_MODEL_BEGIN_CODE + 15
LLM_NEW_CHAT_CODE = VIEW_2_MODEL_BEGIN_CODE + 16
# model 2 view  ========================================================================================================
MODEL_2_VIEW_BEGIN_CODE = 0x70

LOGIN_RSP_CODE = MODEL_2_VIEW_BEGIN_CODE + 0
SESSION_STRING_CODE = MODEL_2_VIEW_BEGIN_CODE + 1
LLM_ANSWER_CODE = MODEL_2_VIEW_BEGIN_CODE + 2
LLM_MODEL_LIST_CODE = MODEL_2_VIEW_BEGIN_CODE + 3
SESSION_VIEW_CONTENT_CODE = MODEL_2_VIEW_BEGIN_CODE + 4
LLM_CHAT_HISTORY_RSP_CODE = MODEL_2_VIEW_BEGIN_CODE + 5
LLM_INLINE_MODEL_LIST_CODE = MODEL_2_VIEW_BEGIN_CODE + 6
LLM_RSP_CHAT_BY_CHAT_ID = MODEL_2_VIEW_BEGIN_CODE + 7
SESSION_INACTIVE_CODE = MODEL_2_VIEW_BEGIN_CODE + 8
RECONNECT_SHELL_FAIL_CODE = MODEL_2_VIEW_BEGIN_CODE + 9

# inner msg type =======================================================================================================
INNER_MSG_BEGIN_CODE = 0x0000


class InnerMsgCode:
    CARRIAGE_RETURN_CODE = INNER_MSG_BEGIN_CODE + 0
    STORE_CURSOR_CODE = INNER_MSG_BEGIN_CODE + 1
    RESTORE_CURSOR_CODE = INNER_MSG_BEGIN_CODE + 2
    CLEAR_SCREEN_CODE = INNER_MSG_BEGIN_CODE + 3
    CLEAR_LINE_CODE = INNER_MSG_BEGIN_CODE + 4
    INSERT_PLAIN_STRING_CODE = INNER_MSG_BEGIN_CODE + 5
    FUNC_R_CODE = INNER_MSG_BEGIN_CODE + 6
    CURSOR_MOVE_TO_CODE = INNER_MSG_BEGIN_CODE + 7
    FONT_STYLE_CODE = INNER_MSG_BEGIN_CODE + 8
    MOVE_CURSOR_UP_CODE = INNER_MSG_BEGIN_CODE + 9
    MOVE_CURSOR_DOWN_CODE = INNER_MSG_BEGIN_CODE + 10
    MOVE_TO_START_OF_NEXT_LINE_CODE = INNER_MSG_BEGIN_CODE + 11
    NEW_LINE_CODE = INNER_MSG_BEGIN_CODE + 12
    TERM_CAP_DELAY_CODE = INNER_MSG_BEGIN_CODE + 13
    KEYBOARD_APP_MODE_ON_CODE = INNER_MSG_BEGIN_CODE + 14
    KEYBOARD_APP_MODE_OFF_CODE = INNER_MSG_BEGIN_CODE + 15
    MOVE_CURSOR_LEFT_CODE = INNER_MSG_BEGIN_CODE + 16
    MOVE_CURSOR_RIGHT_CODE = INNER_MSG_BEGIN_CODE + 17
    FORBIDDEN_CODE = INNER_MSG_BEGIN_CODE + 18
    DEL_CHARS_CODE = INNER_MSG_BEGIN_CODE + 19
    REVERSE_INDEX_CODE = INNER_MSG_BEGIN_CODE + 20
    DCS_SEQUENCE_BEGIN_CODE = INNER_MSG_BEGIN_CODE + 21
    DCS_SEQUENCE_OP_CODE = INNER_MSG_BEGIN_CODE + 22  # 预留操作码，暂时不用
    DCS_SEQUENCE_END_CODE = INNER_MSG_BEGIN_CODE + 23
    RESET_CHAR_SET = INNER_MSG_BEGIN_CODE + 24
    INDEX_CODE = INNER_MSG_BEGIN_CODE + 25
    INSERT_LINES_CODE = INNER_MSG_BEGIN_CODE + 26
    INSERT_BLANKS_CODE = INNER_MSG_BEGIN_CODE + 27
    DEC_RST_CODE = INNER_MSG_BEGIN_CODE + 28
    DEC_SET_CODE = INNER_MSG_BEGIN_CODE + 29
